/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ispan_android_piano_Linux_passive_buzzer */

#ifndef _Included_com_ispan_android_piano_Linux_passive_buzzer
#define _Included_com_ispan_android_piano_Linux_passive_buzzer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ispan_android_piano_Linux_passive_buzzer
 * Method:    open_passive_buzzer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ispan_android_piano_Linux_1passive_1buzzer_open_1passive_1buzzer
  (JNIEnv *, jclass);

/*
 * Class:     com_ispan_android_piano_Linux_passive_buzzer
 * Method:    close_passive_buzzer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ispan_android_piano_Linux_1passive_1buzzer_close_1passive_1buzzer
  (JNIEnv *, jclass);

/*
 * Class:     com_ispan_android_piano_Linux_passive_buzzer
 * Method:    play_run_passive_buzzer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ispan_android_piano_Linux_1passive_1buzzer_play_1run_1passive_1buzzer
  (JNIEnv *, jclass);

/*
 * Class:     com_ispan_android_piano_Linux_passive_buzzer
 * Method:    play_music_passive_buzzer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ispan_android_piano_Linux_1passive_1buzzer_play_1music_1passive_1buzzer
  (JNIEnv *, jclass);

/*
 * Class:     com_ispan_android_piano_Linux_passive_buzzer
 * Method:    send_passive_buzzer
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ispan_android_piano_Linux_1passive_1buzzer_send_1passive_1buzzer
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
